package sqlgen

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

var expectedUpSqlContent = `-- Code generated by protoc-gen-sql. Feel free to modify it as you see fit.

CREATE TABLE IF NOT EXISTS "rukolahasser.test.mymessage" (
    "ts" timestamptz NOT NULL,
    "type_int32" int4,
    "type_uint64" int8,
    "type_bytes" bytea,
    "type_uint256" NUMERIC(78,0),
    "type_array" int4[],
    "type_in8" int2,
    "type_uin8" int2,
    "type_int16" int2,
    "type_uint16" int4,
    "type_uint32" int8,
    "type_int64" int8
);
CREATE INDEX ON "rukolahasser.test.mymessage" ("type_bytes");

`

var (
	sqlDir     string
	binDir     string
	testDir    string
	testTmpDir string
	pluginDir  string
)

func setUp() {
	wd, err := os.Getwd()
	if err != nil {
		log.Fatal("failed to get current working directory")
	}
	testDir = filepath.Join(wd, "../testdata")
	testTmpDir = filepath.Join(testDir, "tmp2")
	sqlDir = filepath.Join(testTmpDir, "sql")
	binDir = filepath.Join(testTmpDir, "bin")
	pluginDir = filepath.Join(wd, "../cmd/protoc-gen-sql")

	err = os.MkdirAll(sqlDir, 0777)
	if err != nil {
		log.Fatal("failed to setup directory")
	}

	err = os.MkdirAll(binDir, 0777)
	if err != nil {
		log.Fatal("failed to setup directory")
	}

	cmd := exec.Command(
		"go",
		"build", "-o", binDir, pluginDir,
	)
	if err = cmd.Run(); err != nil {
		log.Fatal("failed to build protoc-gen-sql")
	}

}

func cleanUp() {
	err := os.RemoveAll(testTmpDir)
	if err != nil {
		log.Fatal("failed to cleanup directory")
	}
}

func TestMain(m *testing.M) {
	setUp()
	exitCode := m.Run()
	cleanUp()
	os.Exit(exitCode)
}

func Test_ExecSQLGenerator(t *testing.T) {
	ExecSQLGenerator(sqlDir, binDir, "dummy", fmt.Sprintf("%s/proto/", testDir), "dummy.proto")

	content, err := ioutil.ReadFile(fmt.Sprintf("%s/dummy.sql", sqlDir))
	if err != nil {
		t.Fatalf("failed to read .sql: %v", err)
	}

	if string(content) != expectedUpSqlContent {
		t.Fatalf("content doesn't match")
	}
}
