package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

var expectedUpSqlContent = `-- Code generated by protoc-gen-sql. Feel free to modify it as you see fit.

CREATE TABLE IF NOT EXISTS "asuka.test.1_2_3.mycontract.rucola" (
    ns TEXT NOT NULL,
    s TEXT NOT NULL,
    "ts" TIMESTAMPTZ NOT NULL,
    "typeint32" INT4,
    "typeuint64" INT8,
    "typebyte" BYTEA,
    "typeuint256" NUMERIC(78,0),
    "typearray" INT4[],
    "typein8" INT2,
    "typeuin8" INT2,
    "typeint16" INT2,
    "typeuint16" INT4,
    "typeuint32" INT8,
    "typeint64" INT8
);

`

var expectedDownSqlContent = `-- Code generated by protoc-gen-sql. Feel free to modify it as you see fit.

DROP TABLE IF EXISTS "common.1_2_3.mycontract.rucola";
`

var (
	sqlDir     string
	binDir     string
	testDir    string
	testTmpDir string
)

func setUp() {
	wd, err := os.Getwd()
	if err != nil {
		log.Fatal("failed to get current working directory")
	}
	testDir = filepath.Join(wd, "../../testdata")
	testTmpDir = filepath.Join(testDir, "tmp")
	sqlDir = filepath.Join(testTmpDir, "sql")
	binDir = filepath.Join(testTmpDir, "bin")

	err = os.MkdirAll(sqlDir, 0777)
	if err != nil {
		log.Fatal("failed to setup directory")
	}

	err = os.MkdirAll(binDir, 0777)
	if err != nil {
		log.Fatal("failed to setup directory")
	}
}

func cleanUp(t *testing.T) {
	t.Cleanup(func() {
		err := os.RemoveAll(testTmpDir)
		if err != nil {
			t.Fatal("failed to cleanup directory")
		}
	})
}

func Test_protoGenUpSql(t *testing.T) {
	setUp()
	defer cleanUp(t)

	cmd := exec.Command(
		"go",
		"build", "-o", binDir, ".",
	)
	if err := cmd.Run(); err != nil {
		t.Errorf("failed to build protoc-gen-sql")
	}

	cmd = exec.Command(
		"protoc",
		fmt.Sprintf("--sql_out=%s", sqlDir), fmt.Sprintf("--plugin=%s/protoc-gen-sql", binDir),
		"--sql_opt=paths=source_relative,file=000000_dummy_test,contract=MyContract,version=1_2_3,package=test,owner=asuka",
		fmt.Sprintf("--proto_path=%s/proto", testDir),
		"dummy.proto",
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("failed generating sql file: %v", stderr.String())
	}

	content, err := ioutil.ReadFile(fmt.Sprintf("%s/000000_dummy_test.up.sql", sqlDir))
	if err != nil {
		t.Fatalf("failed to read .sql: %v", err)
	}

	if string(content) != expectedUpSqlContent {
		t.Fatalf("content doesn't match")
	}
}

func Test_protoGenDownSql(t *testing.T) {
	setUp()
	defer cleanUp(t)

	cmd := exec.Command(
		"go",
		"build", "-o", binDir, ".",
	)
	if err := cmd.Run(); err != nil {
		t.Errorf("failed to build protoc-gen-sql")
	}

	cmd = exec.Command(
		"protoc",
		fmt.Sprintf("--sql_out=%s", sqlDir), fmt.Sprintf("--plugin=%s/protoc-gen-sql", binDir),
		"--sql_opt=paths=source_relative,file=000000_dummy_test,contract=MyContract,version=1_2_3,package=common",
		fmt.Sprintf("-I=%s/proto", testDir),
		"dummy.proto",
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		t.Fatalf("failed generating sql file: %v", stderr.String())
	}

	content, err := ioutil.ReadFile(fmt.Sprintf("%s/000000_dummy_test.down.sql", sqlDir))
	if err != nil {
		t.Fatalf("failed to read .sql: %v", err)
	}

	if string(content) != expectedDownSqlContent {
		t.Fatalf("content doesn't match")
	}
}
